config/routes.rb
Rails.application.routes.draw do

  root  to: 'transports#index'

  resources :transports, shallow: true do
    resources :expenses
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :transport

  validates :date, :kind, :amount, presence: true
  validates :mileage, presence: true,
                      numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/transport.rb
class Transport < ApplicationRecord
  has_many :expenses
  
  validates :name, :mark, :model, :edition_year, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :find_transport, only: [:new, :create]
  def new
    @expense = @transport.expenses.build
  end

  def create
    @expense = @transport.expenses.build(expense_params)

    if @expense.save
      redirect_to transport_path(params[:transport_id])
    else
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:date, :mileage, :kind, :description, :amount)
  end

  def find_transport
    @transport = Transport.find(params[:transport_id])
  end
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :find_transport, only: [:show]

  def index
    @transports = Transport.all
  end

  def show
    @expenses = @transport.expenses
  end

  def new
    @transport = Transport.new
  end

  def create
    @transport = Transport.new(transport_params)

    if @transport.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def find_transport
    @transport = Transport.find(params[:id])
  end

  def transport_params
    params.require(:transport).permit(:name, :mark, :model, :edition_year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/expenses/new.html.slim
= form_with model: [@transport, @expense], local: true do |f|
  p
    => f.label :date, 'Дата:'
    = f.date_field :date
  p
    => f.label :mileage, 'Пробег:'
    = f.number_field :mileage
  p
    => f.label :kind, 'Вид траты:'
    = f.text_field :kind
  p
    => f.label :description, 'Описание:'
    = f.text_field :description
  p
    => f.label :amount, 'Сумма:'
    = f.number_field :amount,
                     value: number_to_currency(f.object.amount.to_f, delimiter: '', unit: ''),
                     step: :any

  p
    = f.submit 'Записать'

app/views/layouts/application.html.slim
doctype html
html
  head
    title MyCarExpenses
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = yield

app/views/transports/_transport.html.slim
tr
  td = link_to transport.name, transport

app/views/transports/index.html.slim
h3 Список транспорта

table
  tbody
    tr
      = render @transports

p
  = link_to 'Добавить транспорт', new_transport_path

app/views/transports/new.html.slim
= form_with model: @transport, local: true do |f|
  p
    => f.label :name, 'Имя:'
    = f.text_field :name
  p
    => f.label :mark, 'Марка:'
    = f.text_field :mark
  p
    => f.label :model, 'Модель:'
    = f.text_field :model
  p
    => f.label :edition_year, 'Год выпуска:'
    = f.number_field :edition_year

  p
    = f.submit 'Создать'

app/views/transports/show.html.slim
h2 Имя: #{@transport.name}

p Марка: #{@transport.mark}

p Модель: #{@transport.model}

p Год выпуска: #{@transport.edition_year}

p
  = link_to 'Внести трату', new_transport_expense_path(@transport)

p
  - @expenses.each do |expense|
    ul
      li = expense.date
      li = expense.mileage
      li = expense.kind
      li = expense.description
      li = expense.amount